// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr7vZZsHH-OWdfm_M1ELPv9Qtpg2QSaZg',
    appId: '1:414273951892:android:f8f517e9b670ebc034bc81',
    messagingSenderId: '414273951892',
    projectId: 'mrdrop-4cd28',
    storageBucket: 'mrdrop-4cd28.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQWh4rnNEaIoqzTSQHzbekgbsTcGkUAP4',
    appId: '1:414273951892:web:8fdecfa3787c0c5234bc81',
    messagingSenderId: '414273951892',
    projectId: 'mrdrop-4cd28',
    authDomain: 'mrdrop-4cd28.firebaseapp.com',
    storageBucket: 'mrdrop-4cd28.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBfaYMiy8CZ_Dp6lqa8_Uu4eZt14I8Okw',
    appId: '1:414273951892:ios:3eae5fbb59e5ea8b34bc81',
    messagingSenderId: '414273951892',
    projectId: 'mrdrop-4cd28',
    storageBucket: 'mrdrop-4cd28.firebasestorage.app',
    iosBundleId: 'com.example.mrdrop',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBfaYMiy8CZ_Dp6lqa8_Uu4eZt14I8Okw',
    appId: '1:414273951892:ios:3eae5fbb59e5ea8b34bc81',
    messagingSenderId: '414273951892',
    projectId: 'mrdrop-4cd28',
    storageBucket: 'mrdrop-4cd28.firebasestorage.app',
    iosBundleId: 'com.example.mrdrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQWh4rnNEaIoqzTSQHzbekgbsTcGkUAP4',
    appId: '1:414273951892:web:02f1e2a0edd79b9734bc81',
    messagingSenderId: '414273951892',
    projectId: 'mrdrop-4cd28',
    authDomain: 'mrdrop-4cd28.firebaseapp.com',
    storageBucket: 'mrdrop-4cd28.firebasestorage.app',
  );

}